### ISSUE TITLE
smartctl-exporter only exporting 1 node

### ISSUE THREAD

**Issue by trieded** [pnnl-miscscripts/miscscripts#51]
It seems like it is not exporting all the nodes for me and only 1 node, is that supposed to be happening?

values.yaml
```
config:
  devices:
  - /dev/sda
  - /dev/nvme0n1

extraInstances: []
#- config:
#    devices:
#    - /dev/nvme0n1
#  nodeSelector:
#    type: other

common:
  config:
    bind_to: "0.0.0.0:9633"
    url_path: "/metrics"
    smartctl_location: /usr/sbin/smartctl
    collect_not_more_than_period: 120s

serviceMonitor:
  enabled: true
  # Specify namespace to load the monitor if not in the same namespace
  namespace: kube-prometheus-stack
  # Add Extra labels if needed. Prometeus operator may need them to find it.
  extraLabels: {}
  release: kube-prometheus-stack

prometheusRules:
  enabled: false
  # Specify namespace to load the monitor if not in the same namespace
  # namespace: prometheus-operator
  # Add Extra labels if needed. Prometeus operator may need them to find it.
  extraLabels: {}
  # release: prometheus-operator

image:
  pullPolicy: IfNotPresent

rbac:
  create: true
  podSecurityPolicy: unrestricted-psp

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- operator: Exists
- effect: NoSchedule
  key: node-role.kubernetes.io/master

affinity: {}

service:
  type: ClusterIP
  port: 80

```
